type Brand<T, B> = T & {__brand: B};

export interface InfoJson {
  type?: string; // this is sometimes set by the frontend, e.g. by the FileUpload module
  title: string;
  author: string;
  copyright: string;
  description: string;
  titleOverride?: string; // uploader-provided name that differs from the .puz/.ipuz file
  authorOverride?: string; // uploader-provided author that differs from the .puz/.ipuz file
}

export interface CluesJson {
  across: string[];
  down: string[];
}

export interface CellData {
  value?: string;
  black?: boolean;
  number?: number;
  revealed?: boolean;
  bad?: boolean;
  good?: boolean;
  pencil?: boolean;
  isHidden?: boolean; // used for fencing mode; if true, then player cannot access the cell at all
  isImage?: boolean; // decorative image cell — part of the word but non-typeable
  solvedBy?: {
    id: string;
    teamId: number;
  };
  parents?: {
    across: number;
    down: number;
  };
}
export type GridData = CellData[][];

export type CellIndex = Brand<number, 'CellIndex'>;
export const toCellIndex = (r: number, c: number, cols: number) => (r * cols + c) as CellIndex;
export type ColoredShade = {index: CellIndex; color: string};
export type ShadeEntry = CellIndex | ColoredShade;

export interface GameJson {
  info: InfoJson;
  grid: GridData;
  teamGrids?: Record<number, GridData>; // TODO move to fencingState.teams[number].grid
  teamClueVisibility?: Record<
    number,
    {
      across: boolean[]; // true --> visible, false --> hidden
      down: boolean[];
    }
  >;
  solution: string[][];
  clues: CluesJson;
  circles?: CellIndex[];
  shades?: ShadeEntry[];
  images?: Record<number, string>;
  contest?: boolean;
}

export interface UserJson {
  id: string;
  cursor?: Cursor;
  displayName: string;
  teamId?: number;
  score?: number;
  misses?: number;
}

export interface Cursor {
  id: string;
  r: number; // Row in puzzle
  c: number; // Column in puzzle
  timestamp: number;
  color?: string;
  active?: boolean;
  displayName?: string;
}

/**
 * PuzzleJson: the json format of puzzles stored in the db
 * Fields are a bit messy & don't correspond perfectly with puzjs formats... see logic in FileUploader.js
 */

export interface PuzzleJson {
  grid: string[][];
  solution: string[][];
  info: InfoJson;
  circles: string[];
  shades: (string | {index: string; color: string})[];
  images?: Record<number, string>;
  clues: CluesJson;
  private?: boolean;
  contest?: boolean;
}

export interface PuzzleStatsJson {
  numSolves: number;
}

export interface AddPuzzleRequest {
  puzzle: PuzzleJson;
  pid?: string; // if not provided, a new one is generated by backend
  isPublic: boolean;
}

export interface AddPuzzleResult {
  pid: string;
  duplicate: boolean;
}

export interface AddPuzzleResponse {
  pid: string;
  duplicate?: boolean;
}

export interface ListPuzzleRequest {
  filter: ListPuzzleRequestFilters;
  page: number;
  pageSize: number;
}

export interface ListPuzzleRequestFilters {
  sizeFilter: {
    Mini: boolean;
    Midi: boolean;
    Standard: boolean;
    Large: boolean;
  };
  nameOrTitleFilter: string;
  typeFilter: {
    Standard: boolean;
    Cryptic: boolean;
    Contest: boolean;
  };
  dayOfWeekFilter: {
    Mon: boolean;
    Tue: boolean;
    Wed: boolean;
    Thu: boolean;
    Fri: boolean;
    Sat: boolean;
    Sun: boolean;
    Unknown: boolean;
  };
}

export interface ListPuzzleResponse {
  puzzles: {
    pid: string;
    content: PuzzleJson;
    stats: PuzzleStatsJson;
    isPublic?: boolean;
  }[];
}

export interface CreateGameResponse {}

export interface CreateGameRequest {
  gid: string;
  pid: string;
  dfac_id?: string;
}

export interface GetGameResponse {
  gid: string;
  title: string;
  author: string;
  duration: number;
  size: string;
}

export interface RecordSolveRequest {
  gid: string;
  time_to_solve: number;
  player_count?: number;
  snapshot?: object;
  keep_replay?: boolean;
}

export interface RecordSolveResponse {}

export type CellCoords = {r: number; c: number};

export interface IncrementGidRequest {}

export interface IncrementGidResponse {
  gid: string;
}

export interface IncrementPidRequest {}

export interface IncrementPidResponse {
  pid: string;
}
